### ISSUE TITLE
encountered an error

### ISSUE THREAD

**Issue by yangsc4063** [url-kaist/outlier-robust-radar-odometry#3]
Using the MulRan parking dataset, I encountered an error. I'm not sure what the problem is. Please advise.
![Screenshot 2023-08-02 16:07:58](https://github.com/url-kaist/outlier-robust-radar-odometry/assets/111360018/e573e54b-5bcf-4ab3-bdfe-c881f332be2c)

**Comment by saadehmd** [comment]
Encountering the same problem with my own dataset collected with the same NavTech radar as in Mulran Dataset (Added some extra logs in there). It seems like there's plenty of extracted features, they just get pruned out during matchFeatures() as none of them shows up as a good match.

Did you find your way around this ?

![image](https://github.com/url-kaist/outlier-robust-radar-odometry/assets/62055851/2535a05e-b204-475e-9211-04397a5c41c4)

**Comment by LimHyungTae** [comment]
Did you make sure to load data from the exact directory?

**Comment by pjlearning** [comment]
I encountered the same error when testing on the KAIST03 seq. Do you know what might be the issue?

**Comment by LimHyungTae** [comment]
Hmm..# of key points are too few. To my knowledge, it should be like < 500.

**Comment by pjlearning** [comment]
> Hmm..# of key points are too few. To my knowledge, it should be like < 500.

Hi LimHyung,

Thank you for your reply! I discovered that the data downloaded from [Mulrun](https://sites.google.com/view/mulran-pr/download?authuser=0) were incorrect. The images were rotated 90 degrees, and the amziths encoded in the images were mostly zeros. I recreated the polar image from the CSV files and was able to run the code without any errors; however, the performance was not satisfactory. Please take a look at the image. Could you help me identify the issues or share the right data download link? I tried both example data and KAIST03 but have the same issues. Thank you!

![Image](https://github.com/user-attachments/assets/5f5a2a2f-ef55-4f6a-a3ac-377efb47566e)

**Comment by pjlearning** [comment]
Hi @LimHyungTae ,

Thank you! I realized the performance degraded because the polar image I recreated was incorrect. Now, it works great for me. Thank you for your excellent work!
